Added counter to SMT
kframework/kore pull request #2172
Opened 2020-09-29 14:15 UTC by MirceaS

---
Fixes #2125 
###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

2020-09-30 14:25 UTC, ttuegel commented on kore/src/SMT.hs
> +            when (counterNew >= 100) reinit
```suggestion
            when (counterNew >= 100) $ (SMT . RWST) $ \ _ _ ->
                    runRWST
                        (getSMT reinit)
                        (SolverInitAndHandle userInit mvar config)
                        counter
```

2020-10-01 00:10 UTC, MirceaS commented
Note: The code currently assumes that `smt` is well behaved in the sense that it puts back the shared variable so that the potential `reinit` doesn't block

2020-10-01 19:26 UTC, ttuegel requested changes
I requested some changes, but I'm going to take care of them right now as part of my clean-up because I think we need it for #2170.

2020-10-01 21:11 UTC, ttuegel approved these changes

2020-10-02 06:45 UTC, merged