Unsatisfiable side condition involving `\forall`: add `translatePredicateForall`
kframework/kore pull request #2181
Opened 2020-10-08 12:47 UTC by andreiburdusa

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

2020-10-09 11:05 UTC, andreiburdusa commented
For the example given in the bug report from the issue, the result is no more
```
/* Spa */
\or{SortGeneratedTopCell{}}(
    /* Created: Kore.Internal.Conditional.makeAndPredicate */
    /* Spa */
    \and{SortGeneratedTopCell{}}(
        /* Created: Kore.Internal.Predicate.makeAndPredicate */
        /* Sfa */
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("false"),
                /* Fl Fn D Sfa */
                Lbl'UndsEqlsEqls'Int'Unds'{}(
                    /* Fl Fn D Sfa */
                    Lbli'LParUndsCommUndsRParUnds'TEST'Unds'Int'Unds'Int'Unds'Int{}(
                        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("1"),
                        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                    ),
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                )
            ),
            /* Sfa */
            \forall{SortGeneratedTopCell{}}(
                ConfigVar'Ques'I:SortInt{},
                /* Sfa */
                \equals{SortInt{}, SortGeneratedTopCell{}}(
                    /* Fl Fn D Sfa */
                    Lbli'LParUndsCommUndsRParUnds'TEST'Unds'Int'Unds'Int'Unds'Int{}(
                        /* Fl Fn D Sfa */ ConfigVar'Ques'I:SortInt{},
                        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                    ),
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                )
            )
        ),
        /* Spa */
        \equals{SortGeneratedTopCell{}, SortGeneratedTopCell{}}(
            /* Fl Fn D Sfa */ VarResult:SortGeneratedTopCell{},
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'generatedTop'-GT-'{}(
                /* Fl Fn D Sfa Cl */
                Lbl'-LT-'k'-GT-'{}(
                    /* Fl Fn D Sfa Cl */
                    kseq{}(
                        /* Fl Fn D Sfa Cl */
                        Lbl'Hash'fail'Unds'TEST'Unds'KItem{}(),
                        /* Fl Fn D Sfa Cl */ dotk{}()
                    )
                ),
                /* Fl Fn D Sfa Cl */
                Lbl'-LT-'generatedCounter'-GT-'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                )
            )
        )
    ),
    /* Created: Kore.Internal.Conditional.makeAndPredicate */
    /* Spa */
    \and{SortGeneratedTopCell{}}(
        /* Created: Kore.Internal.Predicate.makeAndPredicate */
        /* Sfa */
        \and{SortGeneratedTopCell{}}(
            /* Sfa */
            \equals{SortBool{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
                /* Fl Fn D Sfa */
                Lbl'UndsEqlsEqls'Int'Unds'{}(
                    /* Fl Fn D Sfa */
                    Lbli'LParUndsCommUndsRParUnds'TEST'Unds'Int'Unds'Int'Unds'Int{}(
                        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("1"),
                        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                    ),
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                )
            ),
            /* Sfa */
            \forall{SortGeneratedTopCell{}}(
                ConfigVar'Ques'I:SortInt{},
                /* Sfa */
                \equals{SortInt{}, SortGeneratedTopCell{}}(
                    /* Fl Fn D Sfa */
                    Lbli'LParUndsCommUndsRParUnds'TEST'Unds'Int'Unds'Int'Unds'Int{}(
                        /* Fl Fn D Sfa */ ConfigVar'Ques'I:SortInt{},
                        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                    ),
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                )
            )
        ),
        /* Spa */
        \equals{SortGeneratedTopCell{}, SortGeneratedTopCell{}}(
            /* Fl Fn D Sfa */ VarResult:SortGeneratedTopCell{},
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'generatedTop'-GT-'{}(
                /* Fl Fn D Sfa Cl */
                Lbl'-LT-'k'-GT-'{}(/* Fl Fn D Sfa Cl */ dotk{}()),
                /* Fl Fn D Sfa Cl */
                Lbl'-LT-'generatedCounter'-GT-'{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                )
            )
        )
    )
)
```
but 
```
/* Created: Kore.Internal.Conditional.makeAndPredicate */
/* Spa */
\and{SortGeneratedTopCell{}}(
    /* Created: Kore.Internal.Predicate.makeAndPredicate */
    /* Sfa */
    \and{SortGeneratedTopCell{}}(
        /* Sfa */
        \equals{SortBool{}, SortGeneratedTopCell{}}(
            /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortBool{}}("true"),
            /* Fl Fn D Sfa */
            Lbl'UndsEqlsEqls'Int'Unds'{}(
                /* Fl Fn D Sfa */
                Lbli'LParUndsCommUndsRParUnds'TEST'Unds'Int'Unds'Int'Unds'Int{}(
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("1"),
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                ),
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
            )
        ),
        /* Sfa */
        \forall{SortGeneratedTopCell{}}(
            ConfigVar'Ques'I:SortInt{},
            /* Sfa */
            \equals{SortInt{}, SortGeneratedTopCell{}}(
                /* Fl Fn D Sfa */
                Lbli'LParUndsCommUndsRParUnds'TEST'Unds'Int'Unds'Int'Unds'Int{}(
                    /* Fl Fn D Sfa */ ConfigVar'Ques'I:SortInt{},
                    /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
                ),
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
            )
        )
    ),
    /* Spa */
    \equals{SortGeneratedTopCell{}, SortGeneratedTopCell{}}(
        /* Fl Fn D Sfa */ VarResult:SortGeneratedTopCell{},
        /* Fl Fn D Sfa Cl */
        Lbl'-LT-'generatedTop'-GT-'{}(
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'k'-GT-'{}(/* Fl Fn D Sfa Cl */ dotk{}()),
            /* Fl Fn D Sfa Cl */
            Lbl'-LT-'generatedCounter'-GT-'{}(
                /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
            )
        )
    )
)
```
It doesnt have the unsatisfiable branch anymore

2020-10-09 20:48 UTC, ttuegel requested changes
For the integration test, please check in the K definition and spec instead. Please do not check in the SMT transcript.

2020-10-12 19:20 UTC, ttuegel requested changes
The integration test must have a `#Forall`.

2020-10-12 19:20 UTC, ttuegel commented on test/issue-2138/issue-2138-spec.k
> +      requires #assert i ( X, 0 ) ==Int 0
This claim is non-sensical. `#assert` isn't a function, but a constructor.

2020-10-13 19:55 UTC, ttuegel commented on test/issue-2138/issue-2138-spec.k
> +      requires #assert i ( X, 0 ) ==Int 0
Please open a bug with the frontend.

2020-10-19 21:49 UTC, ttuegel approved these changes

2020-10-20 07:49 UTC, merged