changed the dafault state of print-definition and print-pattern of the parser to False
kframework/kore pull request #2273
Opened 2020-11-17 15:38 UTC by MirceaS

Fixes #2264 

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

2020-11-17 16:37 UTC, ttuegel requested changes
Please add unit tests, particularly to check that the combination `--no-print-definition --print-definition` works. You will probably have to move `enableDisableFlag` into the library.

I know that command-line parsing is my favorite example of low-value tests, but I'm starting to change my mind; it's obviously not simple to get command-line parsing right and the tests are easy to write.

2020-11-24 15:51 UTC, MirceaS commented
I updated the type of the parsed options so that it better reflects what we want but since this would break existing code, I aslo added a transformed from the new type to the old.
I believe that code using this type should be refactored so that it uses the new type I introduced, at which point we can get rid of the transformer (`morph`) but if that proves to be too difficult/time consuming we may safely leave it in.

2020-11-24 22:16 UTC, MirceaS commented on kore/app/parser/Main.hs
> -                    lift $ putDoc (debug parsedPattern)
This is just a code refactoring so that it uses the new `KoreParserOptions` type that I introduced

2020-11-25 11:14 UTC, ttuegel requested changes

2020-11-25 11:14 UTC, ttuegel commented on kore/app/parser/Main.hs
> +                        return ()
```suggestion
            Foldable.for_ patternOpt $ \patternOptions -> do
                let PatternOptions { patternFileName } = patternOptions
                parsedPattern <- mainPatternParse patternFileName
                when willVerify $ do
                    let PatternOptions { mainModuleName } = patternOptions
                    indexedModule <-
                        lookupMainModule
                            (ModuleName mainModuleName)
                            indexedModules
                        & lift
                    _ <- mainPatternVerify indexedModule parsedPattern
                    return ()
```

2020-11-25 11:14 UTC, ttuegel commented on kore/src/Kore/OptionsParser.hs
> +module Kore.OptionsParser
Please rename this module `Kore.Options` and make it re-export `Options.Applicative`.

2020-11-25 11:14 UTC, ttuegel commented on kore/src/Kore/OptionsParser.hs
> +
```suggestion
```

2020-11-25 11:14 UTC, ttuegel commented on kore/src/Kore/OptionsParser.hs
> +commandLineParser =
```suggestion
parseKoreParserOptions :: Parser KoreParserOptions
parseKoreParserOptions =
```

2020-11-25 11:14 UTC, ttuegel commented on kore/src/Kore/OptionsParser.hs
> +                )
Please extract this as `parsePatternOptions`.

2020-11-25 11:14 UTC, ttuegel commented on kore/src/Kore/OptionsParser.hs
> +        )
```suggestion
    <*> optional parsePatternOptions
```

2020-11-25 11:14 UTC, ttuegel commented on kore/test/Test/Kore/OptionsParser.hs
> +            let flag_value = willPrintDefinition $ runParser commandLineParser
Please follow the style guide:

```suggestion
            let flagValue = willPrintDefinition $ runParser commandLineParser
```

2020-12-02 19:51 UTC, ttuegel approved these changes

2020-12-02 21:49 UTC, merged