Remove defined marker
kframework/kore pull request #2380
Opened 2021-02-01 09:32 UTC by ana-pantilie

Fixes #2351

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

2021-03-10 11:16 UTC, ana-pantilie commented
@andreiburdusa @ttuegel Sorry, I realized I forgot to add a description to the PR. This made me notice that a few changes could be cleaned up a little and that I was missing some tests. I also fixed the conflicts with master.

2021-03-10 21:57 UTC, ttuegel requested changes

2021-03-10 21:57 UTC, ttuegel commented on kore/src/Kore/Step/Simplification/AndTerms.hs
>          -- TODO (thomas.tuegel): Preserve defined and simplified flags.
```suggestion
        -- TODO (thomas.tuegel): Preserve simplified flags.
```

2021-03-10 21:57 UTC, ttuegel commented on kore/src/Kore/Step/Simplification/Exists.hs
> +                            }
I think this is a little easier to read:

```suggestion
                matched <-
                    normalized
                        { Conditional.substitution = boundSubstitution }
                    & matchesToVariableSubstitution sideCondition variable
                    & lift
```

2021-03-10 21:57 UTC, ttuegel commented on kore/test/Test/Kore/Builtin/Map.hs
>                          ]
Let's extract a helper function for these list elements.

2021-03-11 09:55 UTC, andreiburdusa approved these changes

2021-03-11 21:57 UTC, ttuegel approved these changes

2021-03-12 10:49 UTC, merged