Inefficient Equation renaming
kframework/kore pull request #2438
Opened 2021-03-04 11:44 UTC by andreiburdusa

Fixes #2120 
This pull request addresses the last two checkboxes.

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

2021-03-04 21:47 UTC, ttuegel requested changes

2021-03-04 21:47 UTC, ttuegel commented on kore/src/Kore/Equation/Application.hs
> +  =
```suggestion
attemptEquation sideCondition termLike equation =
    assert  (not $ freeEquationVariableName termLike) $
```

2021-03-04 21:47 UTC, ttuegel commented on kore/src/Kore/Rewriting/RewritingVariable.hs
> +        (from @_ @(Set.Set _) . freeVariables @_ @RewritingVariableName $ pat)
I suggest naming this function `hasFreeEquationVariables`.

2021-03-04 21:47 UTC, ttuegel commented on kore/src/Kore/Unification/Procedure.hs
> +            Conditional () predicate' substitution'
This assertion should appear in `Kore.Equation.Application` after matching and unification on function arguments.

2021-03-05 14:15 UTC, ana-pantilie commented on kore/src/Kore/Equation/Application.hs
> +              $ assert (not . hasFreeEquationVariableName $ predicate)
Could this be factored out? I think it's a little too verbose and it takes longer to read than necessary.

2021-03-05 14:15 UTC, ana-pantilie commented on kore/src/Kore/Equation/Application.hs
> +    assert (not $ hasFreeEquationVariableName termLike) $
Do we ever use `hasFreeEquationVariableName` on its own (without negating it)? Could we just turn `hasFreeEquationVariableName` into `withoutFreeEquationVariables`?

2021-03-10 09:27 UTC, ana-pantilie approved these changes

2021-03-10 09:47 UTC, merged