Distinguish \bottom from stuck states
kframework/kore pull request #2451
Opened 2021-03-10 14:53 UTC by andreiburdusa

Fixes #nnnn

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

2021-03-12 17:26 UTC, ttuegel requested changes

2021-03-12 17:26 UTC, ttuegel commented on kore/src/Kore/Step.hs
> +        if filteredConfigs == mempty
Why not?

```suggestion
        if MultiOr.isBottom filteredConfigs
```

2021-03-15 16:12 UTC, ttuegel approved these changes
I wrote a summary in the pull request description, but please do that in the future.

2021-03-16 09:47 UTC, ana-pantilie approved these changes

2021-03-16 09:48 UTC, ana-pantilie commented on kore/src/Kore/Step.hs
> +        if filteredConfigs == mempty
Sorry, disregard this comment. I added it before you changed this line, but for some reason the review didn't go through.

2021-03-16 14:49 UTC, merged