Warn depth limit exceeded
kframework/kore pull request #2461
Opened 2021-03-12 16:08 UTC by andreiburdusa

Fixes #2449 

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

2021-03-12 16:20 UTC, ttuegel requested changes
Please give your pull request a title and summary following [this advice](https://chris.beams.io/posts/git-commit/).

2021-03-15 16:25 UTC, ttuegel requested changes
Please write a unit test which captures the surprising behavior you found about exceeding the depth limit.

2021-03-16 12:49 UTC, andreiburdusa commented
> Please write a unit test which captures the surprising behavior you found about exceeding the depth limit.

Is there a way to check that a warning is emitted during execution? What surprised me was that we should emit the warning even when the execution would have been stuck anyway at the same step in the absence of the depth limit.

2021-03-17 16:12 UTC, ttuegel approved these changes

2021-03-17 18:54 UTC, merged