Add identity Pattern simplifier
kframework/kore pull request #2953
Opened 2022-01-12 12:53 UTC by andreiburdusa

Fixes #2946 

### Scope: See where the current simplifier can be replaced with an identity simplifier

### Estimate: January 14

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

2022-02-01 09:28 UTC, ana-pantilie requested changes
Running the integration tests twice, once normally and once with `--simplifierx` isn't currently enabled, right? If it's not, this PR needs to enable it. We discussed this is necessary once we merge the first experimental feature.

2022-02-01 09:33 UTC, andreiburdusa commented
> Running the integration tests twice, once normally and once with `--simplifierx` isn't currently enabled, right? If it's not, this PR needs to enable it. We discussed this is necessary once we merge the first experimental feature.

All the integration tests? I thought we don't want to do that because it would take too much time. I probably misunderstood

2022-02-01 09:54 UTC, ana-pantilie commented
> All the integration tests? I thought we don't want to do that because it would take too much time.

It's necessary, otherwise we might break features which we actually use in practice along the way.

2022-02-01 09:56 UTC, ana-pantilie commented
Also, this will probably make Jenkins time out. You'll need to increase the time out period on Jenkins for our CI/integration tests.

2022-02-01 10:36 UTC, andreiburdusa commented
> Also, this will probably make Jenkins time out. You'll need to increase the time out period on Jenkins for our CI/integration tests.

Shoud I try making nix run the integration tests twice as well. or just Jenkins?

2022-02-01 10:41 UTC, ana-pantilie commented
> Shoud I try making nix run the integration tests twice as well, or just Jenkins?

Hmm, let's just run them on Jenkins for now.

2022-02-09 08:47 UTC, ana-pantilie commented on kore/src/Kore/Simplify/Exists.hs
> +    simplifyPatternId,
I think it's best if we move this into `MonadSimplify` as well. This way, we have access to it throughout the simplification code and we won't introduce new module dependencies.

2022-02-09 10:55 UTC, ana-pantilie approved these changes

2022-02-09 15:59 UTC, JKTKops approved these changes

2022-02-10 09:39 UTC, merged